target 'Authorization page' do
  use_frameworks!
    pod 'Alamofire', '~> 4.4'
    pod 'NVActivityIndicatorView'
    pod 'IQKeyboardManagerSwift'
    pod 'AlamofireImage', '~> 3.2'
    pod 'ObjectMapper', '~> 2.2'
    pod 'Cache'
end
